// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY__Lgbgu8XadP8m6iyxhGIqbBAHDlOhU',
    appId: '1:263447377079:web:a5074ff3c3317327198932',
    messagingSenderId: '263447377079',
    projectId: 'chat-app-7466d',
    authDomain: 'chat-app-7466d.firebaseapp.com',
    storageBucket: 'chat-app-7466d.appspot.com',
    measurementId: 'G-2DRCG1EWDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACcykmwVnSek--NX3Efceiqutovsa4O74',
    appId: '1:263447377079:android:4a46a98599de5b88198932',
    messagingSenderId: '263447377079',
    projectId: 'chat-app-7466d',
    storageBucket: 'chat-app-7466d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Fd_5wyI_cBdYz8hgEO_xoIpKdDTqcDI',
    appId: '1:263447377079:ios:cdb60244dc2e8bad198932',
    messagingSenderId: '263447377079',
    projectId: 'chat-app-7466d',
    storageBucket: 'chat-app-7466d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Fd_5wyI_cBdYz8hgEO_xoIpKdDTqcDI',
    appId: '1:263447377079:ios:cdb60244dc2e8bad198932',
    messagingSenderId: '263447377079',
    projectId: 'chat-app-7466d',
    storageBucket: 'chat-app-7466d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY__Lgbgu8XadP8m6iyxhGIqbBAHDlOhU',
    appId: '1:263447377079:web:0ef1bfdb06c439c3198932',
    messagingSenderId: '263447377079',
    projectId: 'chat-app-7466d',
    authDomain: 'chat-app-7466d.firebaseapp.com',
    storageBucket: 'chat-app-7466d.appspot.com',
    measurementId: 'G-842QCP114G',
  );
}
